version: '3'
services:
  app:
    image: app
    container_name: app

    build: .
    deploy: 
      resources:
        limits:
          cpus: "0.15"
          memory: 250M
        reservations:
          cpus: "0.25"
          memory: 128M
    command: yarn start
    environment: 
      - URL_BASE=http://147.182.187.121:4466
      - NODE_ENV=production
      - PORT=4000 
    ports: 
      - 4000:4000

  