# TODO: Remove references to InitialConfig branch and check if the actions/checkout is automatically
# including the contents of the appropiate branch

name: CDdeploy
on:
  push:
    branches:
      - 'main'
      - 'develop'
env:
  PRISMA_MANAGEMENT_API_SECRET: ${{ secrets.PRISMA_MANAGEMENT_API_SECRET}}
  URL_BASE: http://147.182.187.121:4466
  PRISMA_SECRET:  ${{ secrets.PRISMA_SECRET }}
jobs:
  prisma_deploy:
    name: Run Prisma Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Production ENVRIOMENT 
        if: ${{github.ref == 'refs/heads/main'}}
        run: echo "ENVIROMENT=production" >> $GITHUB_ENV
      - name: Development ENVIROMENT
        if: ${{github.ref == 'refs/heads/develop'}}
        run: echo "ENVIROMENT=development" >> $GITHUB_ENV
      - name: Include repo contents in workspace
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Prisma CLI
        run: npm install -g prisma@1.34.10
      - name: Deploy to Prisma Cloud
        run: prisma deploy -p ${{ github.workspace }}/prisma/prisma.yml
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/prisma_mongo:latest